spack:
  include:
  - include.yaml
  view: true
  specs:
  - openfoam@2106_220610+metis
  - waves2foam
  - waveSolvers
  concretizer:
    unify: true
  develop:
    waveSolvers:
      spec: waveSolvers@main
